version: '2'
services:
  magento:
    build: .
    ports:
     - "80"
    volumes:
      - "src:/var/www"
  mysql:
    image: tutum/mysql
    environment:
      - MYSQL_PASS=magento
      - MYSQL_USER=magento
      - ON_CREATE_DB=`magento`
    ports:
      - "3306"